CREATE TABLE user (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	url TEXT NOT NULL,
	username VARCHAR(30),
	password CHAR(40),
	email VARCHAR(50) NOT NULL,
	app TEXT NOT NULL
);
CREATE TABLE app (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	img TEXT NOT NULL,
	url TEXT NOT NULL,
	category VARCHAR(30) NOT NULL,
	star SMALLINT(1),
	author TINYTEXT,
	version VARCHAR(30),
	size INT(30),
	download INT(30)
);
CREATE TABLE review (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	app_id INT NOT NULL,
	review TEXT NOT NULL,
	star SMALLINT(1)
);